import React from 'react';

const TermsAndConditions = () => {
  return (
    <div className="min-h-screen bg-[#E7E7E7] pt-24 pb-16 px-4">
      <div className="max-w-4xl mx-auto bg-white rounded-2xl shadow-md p-6 sm:p-10">
        <h1 className="text-3xl sm:text-4xl font-bold mb-6 text-gray-900 text-center"
            style={{ fontFamily: 'Century Gothic, AppleGothic, sans-serif' }}>
          Terms &amp; Conditions
        </h1>

        <div className="space-y-4 text-sm sm:text-base text-gray-800 leading-relaxed">
          <p>
            This document is an electronic record in terms of the Information Technology Act, 2000 and
            rules thereunder as applicable and the amended provisions pertaining to electronic records
            in various statutes as amended by the Information Technology Act, 2000. This electronic
            record is generated by a computer system and does not require any physical or digital
            signatures.
          </p>

          <p>
            This document is published in accordance with the provisions of Rule 3(1) of the Information
            Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and
            regulations, privacy policy and Terms of Use for access or usage of domain name
            <span className="font-semibold"> https://startupmela.com/ </span>
            (&quot;Website&quot;), including the related mobile site and mobile application
            (hereinafter referred to as the &quot;Platform&quot;).
          </p>

          <p>
            The Platform is owned by NITIN, a company incorporated under the Companies Act, 1956 with
            its registered office at 3505, Mohali Sector 89-D, Rupnagar, India (hereinafter referred to
            as the &quot;Platform Owner&quot;, &quot;we&quot;, &quot;us&quot;, &quot;our&quot;).
          </p>

          <p>
            Your use of the Platform and services and tools are governed by the following terms and
            conditions (&quot;Terms of Use&quot;) as applicable to the Platform including the applicable
            policies which are incorporated herein by way of reference. If you transact on the Platform,
            you shall be subject to the policies that are applicable to the Platform for such
            transaction. By mere use of the Platform, you shall be contracting with the Platform Owner
            and these terms and conditions including the policies constitute your binding obligations
            with the Platform Owner. These Terms of Use relate to your use of our Website, goods (as
            applicable) or services (as applicable) (collectively, the &quot;Services&quot;). Any terms
            and conditions proposed by you which are in addition to or which conflict with these Terms
            of Use are expressly rejected by the Platform Owner and shall be of no force or effect.
            These Terms of Use can be modified at any time without assigning any reason. It is your
            responsibility to periodically review these Terms of Use to stay informed of updates.
          </p>

          <p>
            For the purpose of these Terms of Use, wherever the context so requires &quot;you&quot;,
            &quot;your&quot; or &quot;user&quot; shall mean any natural or legal person who has agreed to
            become a user/buyer on the Platform.
          </p>

          <p className="font-semibold uppercase mt-6">
            Accessing, browsing or otherwise using the Platform indicates your agreement to all the
            terms and conditions under these Terms of Use, so please read the Terms of Use carefully
            before proceeding.
          </p>

          <p className="mt-4 font-semibold">
            The use of the Platform and/or availing of our Services is subject to the following Terms
            of Use:
          </p>

          <ul className="list-disc list-inside space-y-2">
            <li>
              To access and use the Services, you agree to provide true, accurate and complete
              information to us during and after registration, and you shall be responsible for all acts
              done through the use of your registered account on the Platform.
            </li>
            <li>
              Neither we nor any third parties provide any warranty or guarantee as to the accuracy,
              timeliness, performance, completeness or suitability of the information and materials
              offered on this Website or through the Services, for any specific purpose. You acknowledge
              that such information and materials may contain inaccuracies or errors and we expressly
              exclude liability for any such inaccuracies or errors to the fullest extent permitted by
              law.
            </li>
            <li>
              Your use of our Services and the Platform is solely and entirely at your own risk and
              discretion for which we shall not be liable to you in any manner. You are required to
              independently assess and ensure that the Services meet your requirements.
            </li>
            <li>
              The contents of the Platform and the Services are proprietary to us and are licensed to
              us. You will not have any authority to claim any intellectual property rights, title, or
              interest in its contents. The contents include and are not limited to the design, layout,
              look and graphics.
            </li>
            <li>
              You acknowledge that unauthorized use of the Platform and/or the Services may lead to
              action against you as per these Terms of Use and/or applicable laws.
            </li>
            <li>
              You agree to pay us the charges associated with availing the Services.
            </li>
            <li>
              You agree not to use the Platform and/or Services for any purpose that is unlawful, illegal
              or forbidden by these Terms, or Indian or local laws that might apply to you.
            </li>
            <li>
              You agree and acknowledge that the Website and the Services may contain links to other
              third‑party websites. On accessing these links, you will be governed by the terms of use,
              privacy policy and such other policies of such third‑party websites. These links are
              provided for your convenience to provide further information.
            </li>
            <li>
              You understand that upon initiating a transaction for availing the Services you are
              entering into a legally binding and enforceable contract with the Platform Owner for the
              Services.
            </li>
            <li>
              You shall indemnify and hold harmless the Platform Owner, its affiliates, group companies
              (as applicable) and their respective officers, directors, agents, and employees, from any
              claim or demand, or actions including reasonable attorneys&apos; fees, made by any third
              party or penalty imposed due to or arising out of your breach of these Terms of Use, the
              Privacy Policy and other policies, or your violation of any law, rules or regulations or
              the rights (including infringement of intellectual property rights) of a third party.
            </li>
            <li>
              Notwithstanding anything contained in these Terms of Use, the parties shall not be liable
              for any failure to perform an obligation under these Terms if performance is prevented or
              delayed by a force majeure event.
            </li>
            <li>
              These Terms and any dispute or claim relating to it, or its enforceability, shall be
              governed by and construed in accordance with the laws of India.
            </li>
            <li>
              All disputes arising out of or in connection with these Terms shall be subject to the
              exclusive jurisdiction of the courts in Rupnagar and Punjab.
            </li>
            <li>
              All concerns or communications relating to these Terms must be communicated to us using the
              contact information provided on this Website.
            </li>
          </ul>

          <h2 className="text-2xl font-bold mt-10 mb-4 text-gray-900">
            Privacy Policy
          </h2>

          <p>
            This Privacy Policy describes how NITIN and its affiliates (collectively &quot;NITIN&quot;,
            &quot;we&quot;, &quot;our&quot;, &quot;us&quot;) collect, use, share, protect or otherwise
            process your information/personal data through our Website
            <span className="font-semibold"> https://startupmela.com/ </span>
            (hereinafter referred to as the &quot;Platform&quot;). Please note that you may be able to
            browse certain sections of the Platform without registering with us. We do not offer any
            product/service under this Platform outside India and your personal data will primarily be
            stored and processed in India. By visiting this Platform, providing your information or
            availing any product/service offered on the Platform, you expressly agree to be bound by the
            terms and conditions of this Privacy Policy, the Terms of Use and the applicable
            service/product terms and conditions, and agree to be governed by the laws of India
            including but not limited to the laws applicable to data protection and privacy. If you do
            not agree please do not use or access our Platform.
          </p>

          <h3 className="text-xl font-semibold mt-6 mb-2 text-gray-900">
            Collection
          </h3>
          <p>
            We collect your personal data when you use our Platform, Services or otherwise interact with
            us during the course of our relationship and related information provided from time to time.
            Some of the information that we may collect includes but is not limited to personal data/
            information provided to us during sign‑up/registering or using our Platform such as name,
            date of birth, address, telephone/mobile number, email ID and/or any such information shared
            as proof of identity or address. Some of the sensitive personal data may be collected with
            your consent, such as your bank account or credit or debit card or other payment instrument
            information or biometric information such as your facial features or physiological
            information (in order to enable use of certain features when opted for, available on the
            Platform) etc., all of the above being in accordance with applicable law(s).
          </p>
          <p>
            You always have the option to not provide information, by choosing not to use a particular
            service or feature on the Platform. We may track your behaviour, preferences, and other
            information that you choose to provide on our Platform. This information is compiled and
            analysed on an aggregated basis. We will also collect your information related to your
            transactions on the Platform and such third‑party business partner platforms. When such a
            third‑party business partner collects your personal data directly from you, you will be
            governed by their privacy policies. We shall not be responsible for the third‑party business
            partner&apos;s privacy practices or the content of their privacy policies, and we request
            you to read their privacy policies prior to disclosing any information.
          </p>
          <p>
            If you receive an email or a call from a person/association claiming to be NITIN seeking any
            personal data like debit/credit card PIN, net‑banking or mobile banking password, we request
            you to never provide such information. If you have already revealed such information, report
            it immediately to an appropriate law enforcement agency.
          </p>

          <h3 className="text-xl font-semibold mt-6 mb-2 text-gray-900">
            Usage
          </h3>
          <p>
            We use personal data to provide the Services you request. To the extent we use your personal
            data to market to you, we will provide you the ability to opt out of such uses. We use your
            personal data to assist sellers and business partners in handling and fulfilling orders;
            enhancing customer experience; to resolve disputes; troubleshoot problems; inform you about
            online and offline offers, products, services, and updates; customise your experience; detect
            and protect us against error, fraud and other criminal activity; enforce our terms and
            conditions; conduct marketing research, analysis and surveys; and as otherwise described to
            you at the time of collection of information. You understand that your access to these
            products/services may be affected in the event permission is not provided to us.
          </p>

          <h3 className="text-xl font-semibold mt-6 mb-2 text-gray-900">
            Sharing
          </h3>
          <p>
            We may share your personal data internally within our group entities, our other corporate
            entities, and affiliates to provide you access to the services and products offered by them.
            These entities and affiliates may market to you as a result of such sharing unless you
            explicitly opt out. We may disclose personal data to third parties such as sellers, business
            partners, third‑party service providers including logistics partners, prepaid payment
            instrument issuers, third‑party reward programs and other payment methods opted by you.
            These disclosures may be required for us to provide you access to our services and products
            offered to you, to comply with our legal obligations, to enforce our user agreement, to
            facilitate our marketing and advertising activities, to prevent, detect, mitigate, and
            investigate fraudulent or illegal activities related to our services.
          </p>
          <p>
            We may disclose personal and sensitive personal data to government agencies or other
            authorised law enforcement agencies if required to do so by law or in the good faith belief
            that such disclosure is reasonably necessary to respond to subpoenas, court orders, or other
            legal process. We may disclose personal data to law enforcement offices, third‑party rights
            owners, or others in the good faith belief that such disclosure is reasonably necessary to:
            enforce our Terms of Use or Privacy Policy; respond to claims that an advertisement, posting
            or other content violates the rights of a third party; or protect the rights, property or
            personal safety of our users or the general public.
          </p>

          <h3 className="text-xl font-semibold mt-6 mb-2 text-gray-900">
            Security Precautions
          </h3>
          <p>
            To protect your personal data from unauthorised access or disclosure, loss or misuse we
            adopt reasonable security practices and procedures. Once your information is in our
            possession or whenever you access your account information, we adhere to our security
            guidelines to protect it against unauthorised access and offer the use of a secure server.
            However, the transmission of information is not completely secure for reasons beyond our
            control. By using the Platform, the users accept the security implications of data
            transmission over the internet and the World Wide Web which cannot always be guaranteed as
            completely secure, and therefore, there would always remain certain inherent risks regarding
            use of the Platform. Users are responsible for ensuring the protection of login and password
            records for their account.
          </p>

          <h3 className="text-xl font-semibold mt-6 mb-2 text-gray-900">
            Data Deletion and Retention
          </h3>
          <p>
            You have an option to delete your account by visiting your profile and settings on our
            Platform; this action would result in you losing all information related to your account.
            You may also write to us at the contact information provided on the Website to assist you
            with these requests. We may, in the event of any pending grievance, claims, pending
            shipments or any other services, refuse or delay deletion of the account. Once the account
            is deleted, you will lose access to the account.
          </p>
          <p>
            We retain your personal data information for a period no longer than is required for the
            purpose for which it was collected or as required under any applicable law. However, we may
            retain data related to you if we believe it may be necessary to prevent fraud or future abuse
            or for other legitimate purposes. We may continue to retain your data in anonymised form for
            analytical and research purposes.
          </p>

          <h3 className="text-xl font-semibold mt-6 mb-2 text-gray-900">
            Your Rights
          </h3>
          <p>
            You may access, rectify, and update your personal data directly through the functionalities
            provided on the Platform.
          </p>

          <h3 className="text-xl font-semibold mt-6 mb-2 text-gray-900">
            Consent
          </h3>
          <p>
            By visiting our Platform or by providing your information, you consent to the collection,
            use, storage, disclosure and otherwise processing of your information on the Platform in
            accordance with this Privacy Policy. If you disclose to us any personal data relating to
            other people, you represent that you have the authority to do so and permit us to use the
            information in accordance with this Privacy Policy.
          </p>
          <p>
            You, while providing your personal data over the Platform or any partner platforms or
            establishments, consent to us (including our other corporate entities, affiliates, lending
            partners, technology partners, marketing channels, business partners and other third parties)
            to contact you through SMS, instant messaging apps, call and/or e‑mail for the purposes
            specified in this Privacy Policy. You have an option to withdraw your consent that you have
            already provided by writing to the Grievance Officer at the contact information provided
            below, mentioning &quot;Withdrawal of consent for processing personal data&quot; in the
            subject line of your communication. We may verify such requests before acting on your
            request. However, please note that your withdrawal of consent will not be retrospective and
            will be in accordance with the Terms of Use, this Privacy Policy, and applicable laws. In
            the event you withdraw consent given to us under this Privacy Policy, we reserve the right
            to restrict or deny the provision of our services for which we consider such information to
            be necessary.
          </p>

          <h3 className="text-xl font-semibold mt-6 mb-2 text-gray-900">
            Changes to this Privacy Policy
          </h3>
          <p>
            Please check our Privacy Policy periodically for changes. We may update this Privacy Policy
            to reflect changes to our information practices. We may alert/notify you about significant
            changes to the Privacy Policy, in the manner as may be required under applicable laws.
          </p>

          <h2 className="text-2xl font-bold mt-10 mb-4 text-gray-900">
            Refund Policy
          </h2>
          <p>
            We are not providing any kind of refund.
          </p>
        </div>
      </div>
    </div>
  );
};

export default TermsAndConditions;


